In [2]:
!chmod +x setup_olist_db.sh

In [3]:
! ./setup_olist_db.sh

[1/4] Installing PostgreSQL...
./setup_olist_db.sh: line 5: apt-get: command not found

## Python как процедурный язык при работе с PostgreSQL

В контексте взаимодействия с базой данных Python выступает не просто как средство выполнения отдельных SQL-запросов, а как процедурный язык, который управляет всей логикой обработки данных.

В отличие от SQL, который является декларативным языком и описывает, что нужно сделать, Python позволяет задать, как именно должна выполняться операция: пошагово, с учетом условий, ошибок и промежуточных результатов.

### Основная роль Python

Python определяет:

* последовательность выполнения SQL-команд;
* зависимость одних операций от результатов других;
* условия, при которых операция считается успешной или ошибочной;
* момент фиксации (COMMIT) или отката (ROLLBACK) транзакции.

Таким образом, Python выступает как управляющий слой, который координирует работу с базой данных.


### Процедурная логика на практике

При работе с PostgreSQL через Python реализуются классические элементы процедурного программирования:

* последовательность действий
  несколько SQL-запросов выполняются друг за другом как единый сценарий;

* переменные и параметры
  результаты запросов сохраняются и используются в дальнейших шагах;

* условия (if)
  решение о дальнейших действиях принимается на основе данных из базы;

* обработка ошибок (try / except)
  при возникновении ошибки выполняется откат изменений;

* управление транзакцией
  Python явно вызывает:

  * commit() — зафиксировать изменения;
  * rollback() — отменить изменения;
  * SAVEPOINT — зафиксировать промежуточное состояние.


### Разделение ответственности

В связке Python и PostgreSQL роли распределяются следующим образом:

* Python управляет логикой выполнения;
* SQL выполняет операции над данными;
* PostgreSQL обеспечивает транзакционность и целостность.


### Ключевая идея

Python не просто отправляет запросы в базу данных, а управляет целостной операцией как алгоритмом.

Это позволяет реализовывать сложные сценарии:

* выполнение нескольких зависимых действий в рамках одной транзакции;
* принятие решений на основе текущего состояния данных;
* контроль корректности выполнения операций;
* защита от неконсистентных изменений.


### Итог

Использование Python как процедурного языка при работе с PostgreSQL позволяет вынести бизнес-логику на уровень приложения и управлять транзакциями осознанно, контролируя каждый шаг обработки данных.

In [ ]:
import psycopg2

def get_connection():
    return psycopg2.connect(
        dbname='olist_db',
        user='postgres',
        password='postgres',
        host='127.0.0.1',
        port='5432'
    )

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/olist_db')

## Соединение, курсор и поведение транзакций в `psycopg2`

При работе с PostgreSQL через `psycopg2` используются два основных объекта: **соединение (connection)** и **курсор (cursor)**.

### Соединение (connection)

Объект соединения создаётся через `psycopg2.connect(...)` и представляет собой сессию взаимодействия с базой данных.

Через него выполняются ключевые операции управления транзакцией:

* `conn.commit()` — зафиксировать изменения;
* `conn.rollback()` — отменить изменения;
* `conn.close()` — закрыть соединение.

Соединение также определяет границы транзакции.


### Курсор (cursor)

Курсор создаётся из соединения:

```python
cur = conn.cursor()
```

Он используется для выполнения SQL-запросов:

```python
cur.execute("SELECT ...")
```

и получения результатов:

* `fetchone()` — одна строка;
* `fetchall()` — все строки.

Курсор — это инструмент для отправки команд в базу и получения данных, но не управляет транзакцией напрямую.


### Неявное начало транзакции

В `psycopg2` транзакция начинается автоматически при выполнении первого SQL-запроса через `execute()`.

Это означает:

* не требуется явно вызывать `BEGIN`;
* все последующие операции выполняются в рамках одной транзакции;
* транзакция продолжается до тех пор, пока не будет вызван `commit()` или `rollback()`.


### Завершение транзакции

После выполнения операций возможны два сценария:

* если вызван `commit()`, изменения становятся постоянными;
* если вызван `rollback()`, все изменения с момента начала транзакции отменяются.

Если соединение закрывается без явного `commit()`, изменения также не сохраняются.


### Ключевая идея

Соединение определяет границы транзакции,
курсор выполняет SQL-команды,
а Python управляет тем, когда транзакция должна завершиться успешно или быть отменена.

## Задание 1. Простая транзакция с явной фиксацией изменений (`COMMIT`)

### Бизнес-контекст

В таблице `orders` хранится информация о заказах интернет-магазина. Одним из ключевых атрибутов заказа является поле `order_status`, которое отражает текущее состояние обработки заказа.

Приложение должно уметь изменять статус конкретного заказа. Однако само по себе выполнение SQL-команды `UPDATE` ещё не означает, что изменение окончательно сохранено в базе данных. Для завершения операции приложение должно явно зафиксировать результат транзакции.


### Используемая таблица

В задании используется таблица `orders`, содержащая, в частности, следующие поля:

* `order_id` — уникальный идентификатор заказа;
* `customer_id` — идентификатор клиента;
* `order_status` — статус заказа;
* `order_purchase_timestamp` — дата и время оформления заказа;
* `order_approved_at` — дата подтверждения заказа;
* `order_delivered_customer_date` — дата доставки заказа клиенту.


### Постановка задачи

Необходимо реализовать функцию `update_order_status(status, order_id)`, которая принимает:

* `status` — новое значение статуса заказа;
* `order_id` — идентификатор заказа, статус которого необходимо изменить.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. выполнить обновление строки в таблице `orders`;
4. проверить, что обновление действительно затронуло одну из строк;
5. явно зафиксировать изменения с помощью `commit()`;
6. в случае ошибки выполнить `rollback()`.


### Дополнительное условие визуальной проверки результата

Перед вызовом функции и после её выполнения необходимо получить строку из таблицы `orders` для конкретного `order_id` и сравнить значение поля `order_status`.

Таким образом, в задании нужно продемонстрировать полный цикл:

1. получение исходного состояния строки;
2. выполнение транзакционного изменения;
3. фиксацию транзакции через `COMMIT`;
4. повторное чтение строки после завершения операции.


### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Управление транзакцией со стороны Python

Именно код на Python принимает решение о том, когда операция считается завершённой и когда необходимо вызвать `commit()`.

#### 2. Изменение данных в рамках транзакции

SQL-команда `UPDATE` выполняет изменение данных в таблице `orders`, но окончательное сохранение результата зависит от явной фиксации транзакции.

#### 3. Контроль результата SQL-операции

После выполнения `UPDATE` необходимо проверить, была ли изменена хотя бы одна строка. Если строка не найдена, операция должна считаться неуспешной.

#### 4. Наблюдаемость результата

До и после выполнения функции необходимо показать состояние заказа с одним и тем же `order_id`, чтобы убедиться, что после `COMMIT` новое значение статуса действительно сохранилось в базе данных.


### Ограничения

* Запрос на обновление должен быть выполнен как параметризованный;
* Нельзя подставлять значения в SQL через f-строку;
* Нельзя использовать режим автокоммита;
* Обработка ошибок должна быть реализована через `try / except` с вызовом `rollback()`.


### Ожидаемый результат

После выполнения задания:

* для заданного заказа значение `order_status` должно измениться на переданное в параметре `status`;
* изменение должно сохраниться в базе данных только после вызова `commit()`;
* при повторном чтении строки после выполнения функции должно отображаться новое значение статуса.

In [ ]:
def show_order(order_id):
    return pd.read_sql(
        "SELECT * FROM orders WHERE order_id = %(order_id)s",
        engine,
        params={"order_id": order_id}
    )

def update_order_status(status, order_id):

In [ ]:
order_id = 'e481f51cbdc54678b7cc49136f2d6af7'

In [ ]:
show_order(order_id)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18

In [ ]:
update_order_status('processing', order_id)

Соединение открыто. Выполняем операцию обновления статуса заказа.
COMMIT выполнен — статус заказа e481f51cbdc54678b7cc49136f2d6af7 изменен на processing

In [ ]:
show_order(order_id)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,processing,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18

## Задание 2. Откат транзакции при ошибке (`ROLLBACK`)

### Бизнес-контекст

В таблице `orders` хранится информация о заказах интернет-магазина, включая поле `order_status`, которое отражает текущее состояние обработки заказа.

Предположим, что приложение начало изменять статус заказа, но в процессе выполнения бизнес-логики произошла ошибка. Например, после обновления статуса система должна была выполнить ещё одно действие, но оно завершилось сбоем. В такой ситуации изменение не должно остаться в базе данных частично: вся транзакция должна быть отменена.


### Используемая таблица

В задании используется таблица `orders`, содержащая, в частности, следующие поля:

* `order_id` — уникальный идентификатор заказа;
* `customer_id` — идентификатор клиента;
* `order_status` — статус заказа;
* `order_purchase_timestamp` — дата и время оформления заказа.


### Постановка задачи

Необходимо реализовать функцию `update_order_status_with_rollback(status, order_id)`, которая принимает:

* `status` — новое значение статуса заказа;
* `order_id` — идентификатор заказа, статус которого необходимо изменить.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. выполнить обновление поля `order_status` в таблице `orders`;
4. проверить, что обновление действительно затронуло строку;
5. после выполнения `UPDATE` искусственно сгенерировать ошибку на стороне Python;
6. в блоке обработки исключения выполнить `rollback()`;
7. завершить соединение с базой данных.


### Дополнительное условие визуальной проверки результата

Перед вызовом функции и после её выполнения необходимо получить строку из таблицы `orders` по заданному `order_id` и сравнить значение поля `order_status`.

Цель проверки — убедиться, что:

* SQL-команда `UPDATE` действительно была выполнена;
* но после возникновения ошибки и вызова `rollback()` изменение не сохранилось в базе данных.


### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Атомарность транзакции

Если в ходе выполнения транзакции возникает ошибка, все изменения, сделанные внутри неё, должны быть отменены.

#### 2. Управление транзакцией на стороне Python

Код на Python определяет, что операция завершилась неуспешно, и инициирует откат транзакции через `rollback()`.

#### 3. Отличие между выполнением `UPDATE` и сохранением результата

Даже если SQL-команда `UPDATE` была выполнена успешно, изменение не должно считаться сохранённым до тех пор, пока не был вызван `commit()`.

#### 4. Наблюдаемость результата

После завершения функции необходимо повторно прочитать строку из таблицы `orders` и убедиться, что статус заказа остался прежним.


### Ограничения

* запрос на обновление должен быть параметризован;
* нельзя подставлять значения в SQL через f-строку;
* нельзя использовать режим автокоммита;
* ошибка должна возникать после выполнения `UPDATE`, но до вызова `commit()`;
* обработка ошибки должна быть реализована через `try / except` с вызовом `rollback()`.

In [ ]:
def show_order(order_id):
    return pd.read_sql(
        "SELECT order_id, order_status, customer_id, order_purchase_timestamp "
        "FROM orders WHERE order_id = %(order_id)s",
        engine,
        params={"order_id": order_id}
    )

In [ ]:
def update_order_status_with_rollback(status, order_id):

In [ ]:
order_id = '53cdb2fc8bc7dce0b6741e2150273451'

print("Состояние заказа до выполнения функции:")
show_order(order_id)

Состояние заказа до выполнения функции:

,order_id,order_status,customer_id,order_purchase_timestamp
0,53cdb2fc8bc7dce0b6741e2150273451,delivered,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37

In [ ]:
update_order_status_with_rollback('shipped', order_id)

Соединение открыто. Выполняем операцию обновления статуса заказа.
UPDATE выполнен, но транзакция еще не зафиксирована.
ROLLBACK выполнен. Причина: Имитация ошибки в бизнес-логике приложения

In [ ]:
print("Состояние заказа после выполнения функции:")
show_order(order_id)

Состояние заказа после выполнения функции:

,order_id,order_status,customer_id,order_purchase_timestamp
0,53cdb2fc8bc7dce0b6741e2150273451,delivered,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24 20:41:37

## Задание 3. Блокировка строки при конкурентном изменении (`SELECT ... FOR UPDATE`)

### Бизнес-контекст

В таблице `orders` хранится информация о заказах интернет-магазина.  
Предположим, что один и тот же заказ могут одновременно обрабатывать несколько сотрудников или несколько экземпляров приложения. В такой ситуации возникает риск конкурентного изменения одной и той же строки.

Например, один процесс начинает изменять статус заказа, а другой почти одновременно пытается выполнить собственное обновление этой же записи. Если не использовать механизмы блокировки, приложение может столкнуться с несогласованными изменениями и потерей контроля над порядком выполнения операций.

Для предотвращения подобных ситуаций PostgreSQL позволяет явно заблокировать выбранную строку до завершения транзакции с помощью конструкции `SELECT ... FOR UPDATE`.


### Используемая таблица

В задании используется таблица `orders`, содержащая, в частности, следующие поля:

- `order_id` — уникальный идентификатор заказа;
- `customer_id` — идентификатор клиента;
- `order_status` — текущий статус заказа;
- `order_purchase_timestamp` — дата и время создания заказа.


### Постановка задачи

Необходимо реализовать функцию `update_order_status_with_lock(status, order_id)`, которая принимает:

- `status` — новое значение статуса заказа;
- `order_id` — идентификатор заказа, который требуется изменить.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. выбрать строку из таблицы `orders` по заданному `order_id` с использованием `SELECT ... FOR UPDATE`;
4. убедиться, что заказ существует;
5. вывести текущий статус заказа до изменения;
6. выполнить обновление поля `order_status`;
7. явно зафиксировать изменения через `commit()`;
8. в случае ошибки выполнить `rollback()`.


### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Явная блокировка строки

Запрос `SELECT ... FOR UPDATE` блокирует выбранную строку до завершения текущей транзакции.  
Это означает, что другая транзакция не сможет одновременно изменить эту же запись, пока первая транзакция не завершится.

#### 2. Контроль состояния строки до изменения

До выполнения `UPDATE` приложение должно прочитать текущее значение поля `order_status`, чтобы логика изменения опиралась на актуальное состояние данных.

#### 3. Управление блокировкой на стороне транзакции

Блокировка строки существует только в рамках текущей транзакции и снимается после `commit()` или `rollback()`.

#### 4. Управление логикой на стороне Python

Python определяет последовательность действий: сначала блокировка и чтение строки, затем обновление, затем фиксация транзакции.


### Ограничения

- для выбора строки необходимо использовать `SELECT ... FOR UPDATE`;
- SQL-запросы должны быть параметризованными;
- нельзя подставлять значения в SQL через f-строку;
- нельзя использовать режим автокоммита;
- в случае отсутствия заказа необходимо завершить операцию с ошибкой и откатить транзакцию.


### Ожидаемый результат

После выполнения функции:

- строка заказа должна быть выбрана и заблокирована в рамках транзакции;
- поле `order_status` должно измениться на новое значение;
- после `commit()` изменение должно сохраниться в базе данных;
- при повторном чтении строки должно отображаться новое значение статуса.

Дополнительно следует понимать, что в многопользовательской среде такая блокировка защищает запись от одновременного изменения другой транзакцией.

In [ ]:
def show_order(order_id):
    return pd.read_sql(
        """
        SELECT order_id, order_status, customer_id, order_purchase_timestamp
        FROM orders
        WHERE order_id = %(order_id)s
        """,
        engine,
        params={"order_id": order_id}
    )

In [ ]:
def update_order_status_with_lock(status, order_id):

In [ ]:
order_id = 'a4591c265e18cb1dcee52889e2d8acc3'

print("Состояние заказа до выполнения функции:")
show_order(order_id)

Состояние заказа до выполнения функции:

,order_id,order_status,customer_id,order_purchase_timestamp
0,a4591c265e18cb1dcee52889e2d8acc3,delivered,503740e9ca751ccdda7ba28e9ab8f608,2017-07-09 21:57:05

In [ ]:
update_order_status_with_lock('shipped', order_id)

Соединение открыто. Начинаем транзакцию с блокировкой строки.
Текущий статус заказа a4591c265e18cb1dcee52889e2d8acc3: delivered
COMMIT выполнен — статус заказа a4591c265e18cb1dcee52889e2d8acc3 изменен на delivered

In [ ]:
print("Состояние заказа после выполнения функции:")
show_order(order_id)

Состояние заказа после выполнения функции:

,order_id,order_status,customer_id,order_purchase_timestamp
0,a4591c265e18cb1dcee52889e2d8acc3,delivered,503740e9ca751ccdda7ba28e9ab8f608,2017-07-09 21:57:05

## Задание 4. Частичный откат транзакции с использованием `SAVEPOINT`

### Бизнес-контекст

В прикладных системах нередко встречаются многоэтапные операции, в которых одни действия являются обязательными, а другие — дополнительными. Если ошибка возникает на дополнительном шаге, не всегда требуется отменять всю транзакцию целиком. В таких случаях используется механизм точек сохранения (`SAVEPOINT`).

Предположим, что приложение выполняет обработку заказа в два этапа:

1. основной этап — изменение статуса заказа;
2. дополнительный этап — изменение даты подтверждения заказа.

Если на втором этапе происходит ошибка, приложение должно отменить только этот дополнительный шаг, сохранив результат основного изменения.


### Используемая таблица

В задании используется таблица `orders`, содержащая, в частности, следующие поля:

- `order_id` — уникальный идентификатор заказа;
- `order_status` — текущий статус заказа;
- `order_approved_at` — дата и время подтверждения заказа;
- `order_purchase_timestamp` — дата и время создания заказа.


### Постановка задачи

Необходимо реализовать функцию `update_order_with_savepoint(status, approved_at, order_id)`, которая принимает:

- `status` — новое значение статуса заказа;
- `approved_at` — новое значение даты подтверждения заказа;
- `order_id` — идентификатор заказа, который требуется изменить.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. обновить поле `order_status` для заданного заказа;
4. убедиться, что строка существует;
5. создать точку сохранения с помощью `SAVEPOINT`;
6. попытаться выполнить второй шаг — обновление поля `order_approved_at`;
7. искусственно сгенерировать ошибку после второго шага, чтобы продемонстрировать частичный откат;
8. выполнить `ROLLBACK TO SAVEPOINT`, отменив только второй шаг;
9. завершить транзакцию с помощью `commit()`, сохранив основной результат.


### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Точка сохранения внутри транзакции

`SAVEPOINT` позволяет зафиксировать промежуточное состояние транзакции, к которому можно вернуться без отмены всех ранее выполненных действий.

#### 2. Частичный откат

Если ошибка возникает после `SAVEPOINT`, приложение может отменить только часть изменений, выполненных после этой точки.

#### 3. Управление транзакцией на стороне Python

Python определяет, какие действия являются обязательными, а какие — дополнительными, и принимает решение о том, какую часть транзакции следует сохранить, а какую — отменить.

#### 4. Отличие `ROLLBACK TO SAVEPOINT` от полного `ROLLBACK`

Полный `rollback()` отменяет все изменения в транзакции, тогда как `ROLLBACK TO SAVEPOINT` отменяет только действия, выполненные после указанной точки сохранения.


### Ограничения

- SQL-запросы должны быть параметризованными;
- нельзя подставлять значения в SQL через f-строку;
- нельзя использовать режим автокоммита;
- ошибка должна возникать после создания `SAVEPOINT` и после выполнения второго шага;
- после частичного отката транзакция должна завершаться через `commit()`.


### Ожидаемый результат

После выполнения функции:

- значение поля `order_status` должно измениться и сохраниться в базе данных;
- изменение поля `order_approved_at`, выполненное после `SAVEPOINT`, не должно сохраниться;
- итоговое состояние строки должно показывать, что основной шаг завершён успешно, а дополнительный шаг был отменён.

In [ ]:
def show_order_with_approval(order_id):
    return pd.read_sql(
        """
        SELECT
            order_id,
            order_status,
            order_approved_at,
            order_purchase_timestamp
        FROM orders
        WHERE order_id = %(order_id)s
        """,
        engine,
        params={"order_id": order_id}
    )

In [ ]:
def update_order_with_savepoint(status, approved_at, order_id):

In [ ]:
order_id = '76c6e866289321a7c93b82b54852dc33'

print("Состояние заказа до выполнения функции:")
show_order_with_approval(order_id)

Состояние заказа до выполнения функции:

,order_id,order_status,order_approved_at,order_purchase_timestamp
0,76c6e866289321a7c93b82b54852dc33,delivered,2017-01-25 02:50:47,2017-01-23 18:29:09

In [ ]:
update_order_with_savepoint(
    status='approved',
    approved_at='2017-10-10 10:00:00',
    order_id=order_id
)

Соединение открыто. Начинаем многоэтапную транзакцию.
Основной шаг выполнен: статус заказа 76c6e866289321a7c93b82b54852dc33 изменен на approved
Точка сохранения создана.
Дополнительный шаг выполнен: дата подтверждения обновлена.
Выполнен частичный откат к точке сохранения.
COMMIT выполнен — основной результат по заказу 76c6e866289321a7c93b82b54852dc33 сохранен.

In [ ]:
print("Состояние заказа после выполнения функции:")
show_order_with_approval(order_id)

Состояние заказа после выполнения функции:

,order_id,order_status,order_approved_at,order_purchase_timestamp
0,76c6e866289321a7c93b82b54852dc33,approved,2017-01-25 02:50:47,2017-01-23 18:29:09

## Задание 5. Принятие решения в Python на основе результата SQL-запроса

### Бизнес-контекст

В прикладных системах база данных часто используется не только для хранения данных, но и как источник информации для принятия решений на стороне приложения. В этом случае SQL отвечает за получение и вычисление необходимых показателей, а Python — за интерпретацию результата и выбор дальнейшего сценария действий.

Предположим, что приложение должно определить, следует ли пометить заказ как приоритетный для обработки. Такое решение принимается на основании общей суммы оплат по заказу.

Если суммарное значение платежей по заказу превышает заданный порог, заказ получает специальный статус. Если сумма недостаточна, статус изменяться не должен.


### Используемые таблицы

В задании используются две таблицы.

#### Таблица `orders`

Содержит сведения о заказах, в том числе:

- `order_id` — уникальный идентификатор заказа;
- `customer_id` — идентификатор клиента;
- `order_status` — текущий статус заказа;
- `order_purchase_timestamp` — дата и время оформления заказа.

#### Таблица `order_payments`

Содержит сведения об оплатах, связанных с заказами, в том числе:

- `order_id` — идентификатор заказа;
- `payment_sequential` — номер платежа в рамках заказа;
- `payment_type` — тип оплаты;
- `payment_installments` — количество платежей;
- `payment_value` — сумма оплаты.


### Постановка задачи

Необходимо реализовать функцию `update_order_status_by_payment(status, threshold, order_id)`, которая принимает:

- `status` — значение статуса, которое следует установить заказу при выполнении условия;
- `threshold` — пороговое значение суммы оплат;
- `order_id` — идентификатор заказа, который требуется проверить.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. получить суммарное значение оплат по заданному заказу из таблицы `order_payments`;
4. проверить, существует ли заказ в таблице `orders`;
5. сравнить рассчитанную сумму оплат с переданным порогом;
6. если сумма превышает порог, обновить поле `order_status` в таблице `orders`;
7. если сумма не превышает порог, не выполнять `UPDATE`, но корректно завершить транзакцию;
8. в случае ошибки выполнить `rollback()`.


### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Разделение ролей между SQL и Python

SQL используется для вычисления агрегированного показателя — общей суммы оплат по заказу.  
Python использует полученное значение для принятия решения о дальнейших действиях.

#### 2. Управление логикой на стороне приложения

Именно Python определяет, будет ли выполнено изменение статуса, исходя из бизнес-правила, связанного с пороговым значением.

#### 3. Использование результата SQL-запроса в процедурной логике

Значение, полученное из базы данных, сохраняется в переменную Python и становится основанием для ветвления через условный оператор `if`.

#### 4. Контроль целостности операции

Если заказ не существует, операция должна завершаться с ошибкой.  
Если заказ существует, но сумма оплат недостаточна, статус не изменяется, а транзакция завершается без ошибки.


### Ограничения

- SQL-запросы должны быть параметризованными;
- нельзя подставлять значения в SQL через f-строку;
- нельзя использовать режим автокоммита;
- для расчета суммы оплат необходимо использовать агрегатную функцию `SUM`;
- при отсутствии оплат должно использоваться значение `0`, а не `NULL`.


### Ожидаемый результат

После выполнения функции возможны два сценария:

1. если сумма оплат по заказу больше порога `threshold`, поле `order_status` должно измениться на переданное значение `status`;
2. если сумма оплат по заказу не превышает порог, значение `order_status` должно остаться без изменений.

В обоих случаях приложение должно корректно завершить работу с транзакцией.

In [ ]:
def show_order_with_payment(order_id):
    return pd.read_sql(
        """
        SELECT
            o.order_id,
            o.order_status,
            o.customer_id,
            COALESCE(SUM(op.payment_value), 0) AS total_payment
        FROM orders o
        LEFT JOIN order_payments op
            ON o.order_id = op.order_id
        WHERE o.order_id = %(order_id)s
        GROUP BY
            o.order_id,
            o.order_status,
            o.customer_id
        """,
        engine,
        params={"order_id": order_id}
    )

In [ ]:
def update_order_status_by_payment(status, threshold, order_id):

In [ ]:
order_id = 'e6ce16cb79ec1d90b1da9085a6118aeb'

print("Состояние заказа до выполнения функции:")
display(show_order_with_payment(order_id))

update_order_status_by_payment(
    status='priority',
    threshold=50,
    order_id=order_id
)

print("Состояние заказа после выполнения функции:")
display(show_order_with_payment(order_id))

Состояние заказа до выполнения функции:

,order_id,order_status,customer_id,total_payment
0,e6ce16cb79ec1d90b1da9085a6118aeb,priority,494dded5b201313c64ed7f100595b95c,259.06

Соединение открыто. Анализируем сумму оплат по заказу.
Сумма оплат по заказу e6ce16cb79ec1d90b1da9085a6118aeb: 259.06
Условие выполнено: сумма оплат больше 50. Статус будет изменен на priority.
COMMIT выполнен.
Состояние заказа после выполнения функции:

,order_id,order_status,customer_id,total_payment
0,e6ce16cb79ec1d90b1da9085a6118aeb,priority,494dded5b201313c64ed7f100595b95c,259.06

In [ ]:
order_id = '53cdb2fc8bc7dce0b6741e2150273451'

print("Состояние заказа до выполнения функции:")
display(show_order_with_payment(order_id))

update_order_status_by_payment(
    status='priority',
    threshold=1000,
    order_id=order_id
)

print("Состояние заказа после выполнения функции:")
display(show_order_with_payment(order_id))

Состояние заказа до выполнения функции:

,order_id,order_status,customer_id,total_payment
0,53cdb2fc8bc7dce0b6741e2150273451,delivered,b0830fb4747a6c6d20dea0b8c802d7ef,141.46

Соединение открыто. Анализируем сумму оплат по заказу.
Сумма оплат по заказу 53cdb2fc8bc7dce0b6741e2150273451: 141.46
Условие выполнено: сумма оплат больше 1. Статус будет изменен на priority.
COMMIT выполнен.
Состояние заказа после выполнения функции:

,order_id,order_status,customer_id,total_payment
0,53cdb2fc8bc7dce0b6741e2150273451,priority,b0830fb4747a6c6d20dea0b8c802d7ef,141.46