In [ ]:
!chmod +x setup_olist_db.sh

In [ ]:
! ./setup_olist_db.sh

In [ ]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/olist_db')

def get_connection():
    conn = psycopg2.connect(
        host='127.0.0.1',
        port='5432',
        dbname='olist_db',
        user='postgres',
        password='postgres'
    )
    conn.autocommit = False
    return conn

## Задание 1. Отмена заказа со статусом `processing` (Транзакция с проверкой состояния)

### Бизнес-контекст

В таблице `orders` хранится информация о заказах интернет-магазина, включая текущее состояние каждого заказа в поле `order_status`.

Покупатель может обратиться в поддержку с просьбой отменить заказ. Однако отмена допустима не на любом этапе обработки. В рамках данного задания будем считать, что заказ можно отменить только в том случае, если он находится в статусе `processing`, то есть еще обрабатывается и не передан в доставку.

Если заказ уже отправлен, доставлен или находится в ином состоянии, такая операция через данную функцию выполняться не должна.

### Используемая таблица

В задании используется таблица `orders`, содержащая, в частности, следующие поля:

* `order_id` — уникальный идентификатор заказа;
* `customer_id` — идентификатор клиента;
* `order_status` — текущий статус заказа;
* `order_purchase_timestamp` — дата и время оформления заказа;
* `order_approved_at` — дата подтверждения заказа;
* `order_delivered_carrier_date` — дата передачи заказа в доставку;
* `order_delivered_customer_date` — дата доставки заказа клиенту.

### Постановка задачи

Необходимо реализовать функцию `cancel_processing_order(order_id)`, которая принимает:

* `order_id` — идентификатор заказа, который требуется отменить.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. получить текущий статус заказа из таблицы `orders`;
4. проверить, существует ли заказ с указанным `order_id`;
5. если заказ найден и его статус равен `processing`, изменить статус на `canceled`;
6. явно зафиксировать изменения с помощью `commit()`;
7. если заказ не найден или его статус отличается от `processing`, выполнить `rollback()`;
8. в случае ошибки также выполнить `rollback()`.

### Дополнительное условие визуальной проверки результата

Перед вызовом функции и после её выполнения необходимо получить строку из таблицы `orders` для одного и того же `order_id` и сравнить значение поля `order_status`.

Таким образом, в задании нужно продемонстрировать полный цикл:

1. получение исходного состояния строки;
2. проверку текущего статуса заказа;
3. выполнение транзакционного изменения;
4. фиксацию транзакции через `COMMIT`;
5. повторное чтение строки после завершения операции.

### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Управление транзакцией со стороны Python

Именно Python-код определяет, можно ли завершить операцию успешно, и принимает решение о вызове `commit()` или `rollback()`.

#### 2. Проверка состояния данных перед изменением

Перед выполнением `UPDATE` нужно убедиться, что заказ действительно находится в допустимом статусе `processing`.

#### 3. Контроль результата чтения из базы данных

После выполнения `SELECT` необходимо проверить, что заказ с указанным `order_id` существует. Если строка не найдена, операция должна считаться неуспешной.

#### 4. Наблюдаемость результата

До и после вызова функции необходимо показать строку с одним и тем же `order_id`, чтобы убедиться, что после `COMMIT` статус действительно изменился с `processing` на `canceled`.

### Ограничения

* Запросы должны быть выполнены как параметризованные;
* Нельзя подставлять значения в SQL через f-строку;
* Нельзя использовать режим автокоммита;
* Обработка ошибок должна быть реализована через `try / except` с вызовом `rollback()`;
* Если заказ не найден, операция должна завершаться без изменения данных;
* Если статус заказа отличается от `processing`, операция также не должна изменять данные.

### Ожидаемый результат

После выполнения задания:

* для заданного заказа со статусом `processing` значение `order_status` должно измениться на `canceled`;
* изменение должно сохраниться в базе данных только после вызова `commit()`;
* если заказ не найден или имеет другой статус, изменение не должно быть выполнено;
* при повторном чтении строки после выполнения функции должно отображаться новое значение статуса только в корректном случае.

In [ ]:
def show_order(order_id):
    return pd.read_sql(
        """
        SELECT
            order_id,
            customer_id,
            order_status,
            order_purchase_timestamp,
            order_approved_at,
            order_delivered_carrier_date,
            order_delivered_customer_date
        FROM orders
        WHERE order_id = %(order_id)s
        """,
        engine,
        params={"order_id": order_id}
    )


def cancel_processing_order(order_id):

In [ ]:
order_id = 'd3c8851a6651eeff2f73b0e011ac45d0'

print("Состояние заказа ДО выполнения функции:")
show_order(order_id)

Состояние заказа ДО выполнения функции:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
0,d3c8851a6651eeff2f73b0e011ac45d0,957f8e082185574de25992dc659ebbc0,processing,2016-10-05 22:44:13,2016-10-06 15:51:05,None,None

In [ ]:
cancel_processing_order(order_id)

Попытка отмены заказа d3c8851a6651eeff2f73b0e011ac45d0...
Текущий статус заказа: processing
COMMIT выполнен — статус заказа d3c8851a6651eeff2f73b0e011ac45d0 изменен с processing на canceled

In [ ]:
print("Состояние заказа ПОСЛЕ выполнения функции:")
show_order(order_id)

Состояние заказа ПОСЛЕ выполнения функции:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
0,d3c8851a6651eeff2f73b0e011ac45d0,957f8e082185574de25992dc659ebbc0,canceled,2016-10-05 22:44:13,2016-10-06 15:51:05,None,None

## Задание 2. Заполнение пустого заголовка отзыва (`COMMIT` с предварительной проверкой)

### Бизнес-контекст

В таблице `order_reviews` хранятся отзывы клиентов по заказам интернет-магазина.  
Отзыв может содержать числовую оценку, текст комментария и короткий заголовок в поле `review_comment_title`.

На практике возможна ситуация, когда отзыв уже существует, но поле заголовка осталось пустым.  
Приложение должно уметь дополнять такой отзыв заголовком. Однако изменять запись можно только в том случае, если:

1. отзыв по указанному заказу действительно существует;
2. заголовок у этого отзыва пока не заполнен.

Если отзыв не найден или заголовок уже задан, операция не должна изменять данные.

### Используемая таблица

В задании используется таблица `order_reviews`, содержащая, в частности, следующие поля:

* `review_id` — идентификатор отзыва;
* `order_id` — идентификатор заказа;
* `review_score` — оценка заказа;
* `review_comment_title` — заголовок отзыва;
* `review_comment_message` — текст отзыва;
* `review_creation_date` — дата создания отзыва;
* `review_answer_timestamp` — дата ответа на отзыв.

### Постановка задачи

Необходимо реализовать функцию `update_review_title(order_id, new_title)`, которая принимает:

* `order_id` — идентификатор заказа, для которого нужно обновить заголовок отзыва;
* `new_title` — новый заголовок отзыва.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. найти отзыв по указанному `order_id`;
4. проверить, существует ли такой отзыв;
5. проверить, что поле `review_comment_title` пока не заполнено;
6. если отзыв найден и заголовок пустой, обновить поле `review_comment_title`;
7. явно зафиксировать изменения с помощью `commit()`;
8. если отзыв не найден или заголовок уже заполнен, выполнить `rollback()`;
9. в случае ошибки также выполнить `rollback()`.

### Дополнительное условие визуальной проверки результата

Перед вызовом функции и после её выполнения необходимо получить строку из таблицы `order_reviews` для одного и того же `order_id` и сравнить значение поля `review_comment_title`.

Таким образом, в задании нужно продемонстрировать полный цикл:

1. получение исходного состояния строки;
2. проверку существования отзыва;
3. проверку текущего значения `review_comment_title`;
4. выполнение транзакционного изменения;
5. фиксацию транзакции через `COMMIT`;
6. повторное чтение строки после завершения операции.

### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Управление транзакцией со стороны Python

Именно Python-код определяет, можно ли завершить операцию успешно, и принимает решение о вызове `commit()` или `rollback()`.

#### 2. Проверка состояния данных перед изменением

Перед выполнением `UPDATE` нужно убедиться, что отзыв существует и что заголовок ещё не заполнен.

#### 3. Контроль результата чтения из базы данных

После выполнения `SELECT` необходимо проверить, что отзыв по указанному `order_id` найден. Если строка отсутствует, операция должна считаться неуспешной.

#### 4. Наблюдаемость результата

До и после вызова функции необходимо показать строку с одним и тем же `order_id`, чтобы убедиться, что после `COMMIT` поле `review_comment_title` действительно изменилось.

### Ограничения

* Запросы должны быть выполнены как параметризованные;
* Нельзя подставлять значения в SQL через f-строку;
* Нельзя использовать режим автокоммита;
* Обработка ошибок должна быть реализована через `try / except` с вызовом `rollback()`;
* Если отзыв не найден, операция должна завершаться без изменения данных;
* Если заголовок уже заполнен, операция также не должна изменять данные.

### Ожидаемый результат

После выполнения задания:

* для заданного заказа с существующим отзывом и пустым `review_comment_title` значение этого поля должно измениться на переданное в параметре `new_title`;
* изменение должно сохраниться в базе данных только после вызова `commit()`;
* если отзыв не найден или заголовок уже был заполнен, изменение не должно быть выполнено;
* при повторном чтении строки после выполнения функции должно отображаться новое значение заголовка только в корректном случае.

In [ ]:
def show_review(order_id):
    return pd.read_sql(
        """
        SELECT
            review_id,
            order_id,
            review_score,
            review_comment_title,
            review_comment_message,
            review_creation_date,
            review_answer_timestamp
        FROM order_reviews
        WHERE order_id = %(order_id)s
        """,
        engine,
        params={"order_id": order_id}
    )


def update_review_title(order_id, new_title):

In [ ]:
order_id = '73fc7af87114b39712e6da79b0a377eb'

print("Состояние отзыва ДО выполнения функции:")
show_review(order_id)

Состояние отзыва ДО выполнения функции:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,None,2018-01-18,2018-01-18 21:46:59

In [ ]:
update_review_title(
    order_id=order_id,
    new_title='Отличный сервис'
)

Пытаемся обновить заголовок отзыва для заказа 73fc7af87114b39712e6da79b0a377eb...
Найден отзыв 7bc2406110b926393aa56f80a40eba40
Текущий заголовок: None
COMMIT выполнен — заголовок отзыва для заказа 73fc7af87114b39712e6da79b0a377eb обновлен

In [ ]:
print("Состояние отзыва ПОСЛЕ выполнения функции:")
show_review(order_id)

Состояние отзыва ПОСЛЕ выполнения функции:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Отличный сервис,None,2018-01-18,2018-01-18 21:46:59

## Задание 3. Изменение цены позиции заказа с проверкой бизнес-ограничения

### Бизнес-контекст

В таблице `order_items` хранятся позиции заказов интернет-магазина.  
Каждая строка соответствует отдельной товарной позиции внутри заказа и содержит, в частности, цену товара в поле `price`.

Иногда приложению требуется скорректировать цену конкретной позиции заказа. Однако в рамках данного задания будем считать, что система не разрешает устанавливать цену выше 5000 условных единиц. Кроме того, цена должна быть положительной.

Таким образом, изменение допустимо только при выполнении двух условий:

1. позиция заказа с указанными идентификаторами существует;
2. новое значение цены больше 0 и не превышает 5000.

Если хотя бы одно из этих условий нарушено, операция не должна изменять данные.

### Используемая таблица

В задании используется таблица `order_items`, содержащая, в частности, следующие поля:

* `order_id` — идентификатор заказа;
* `order_item_id` — номер позиции внутри заказа;
* `product_id` — идентификатор товара;
* `seller_id` — идентификатор продавца;
* `shipping_limit_date` — предельная дата отправки;
* `price` — цена товарной позиции;
* `freight_value` — стоимость доставки.

### Постановка задачи

Необходимо реализовать функцию `update_item_price(order_id, order_item_id, new_price)`, которая принимает:

* `order_id` — идентификатор заказа;
* `order_item_id` — номер позиции в заказе;
* `new_price` — новое значение цены.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. найти строку в таблице `order_items` по паре `(order_id, order_item_id)`;
4. проверить, существует ли такая позиция;
5. проверить, что новое значение `new_price` больше 0 и не превышает 5000;
6. если позиция найдена и новое значение допустимо, обновить поле `price`;
7. явно зафиксировать изменения с помощью `commit()`;
8. если позиция не найдена или цена нарушает ограничение, выполнить `rollback()`;
9. в случае ошибки также выполнить `rollback()`.

### Дополнительное условие визуальной проверки результата

Перед вызовом функции и после её выполнения необходимо получить строку из таблицы `order_items` для одной и той же позиции заказа и сравнить значение поля `price`.

Таким образом, в задании нужно продемонстрировать полный цикл:

1. получение исходного состояния строки;
2. проверку существования позиции заказа;
3. проверку допустимости нового значения цены;
4. выполнение транзакционного изменения;
5. фиксацию транзакции через `COMMIT`;
6. повторное чтение строки после завершения операции.

### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Управление транзакцией со стороны Python

Именно Python-код определяет, можно ли завершить операцию успешно, и принимает решение о вызове `commit()` или `rollback()`.

#### 2. Проверка бизнес-ограничения перед изменением

Перед выполнением `UPDATE` нужно убедиться, что цена находится в допустимом диапазоне.

#### 3. Контроль результата чтения из базы данных

После выполнения `SELECT` необходимо проверить, что позиция заказа с указанными `(order_id, order_item_id)` существует. Если строка не найдена, операция должна считаться неуспешной.

#### 4. Наблюдаемость результата

До и после вызова функции необходимо показать одну и ту же строку таблицы `order_items`, чтобы убедиться, что после `COMMIT` поле `price` действительно изменилось.

### Ограничения

* Запросы должны быть выполнены как параметризованные;
* Нельзя подставлять значения в SQL через f-строку;
* Нельзя использовать режим автокоммита;
* Обработка ошибок должна быть реализована через `try / except` с вызовом `rollback()`;
* Если позиция заказа не найдена, операция должна завершаться без изменения данных;
* Если `new_price <= 0` или `new_price > 5000`, операция также не должна изменять данные.

### Ожидаемый результат

После выполнения задания:

* для заданной позиции заказа значение `price` должно измениться на переданное в параметре `new_price`, если оно допустимо;
* изменение должно сохраниться в базе данных только после вызова `commit()`;
* если позиция не найдена или новое значение цены нарушает ограничение, изменение не должно быть выполнено;
* при повторном чтении строки после выполнения функции должно отображаться новое значение цены только в корректном случае.

In [ ]:
def show_order_item(order_id, order_item_id):
    return pd.read_sql(
        """
        SELECT
            order_id,
            order_item_id,
            product_id,
            seller_id,
            shipping_limit_date,
            price,
            freight_value
        FROM order_items
        WHERE order_id = %(order_id)s
          AND order_item_id = %(order_item_id)s
        """,
        engine,
        params={
            "order_id": order_id,
            "order_item_id": order_item_id
        }
    )


def update_item_price(order_id, order_item_id, new_price):

In [ ]:
order_id = '00010242fe8c5a6d1ba2dd792cb16214'
order_item_id = 1

In [ ]:
print("Состояние позиции ДО выполнения функции:")
show_order_item(order_id, order_item_id)

Состояние позиции ДО выполнения функции:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29

In [ ]:
update_item_price(
    order_id=order_id,
    order_item_id=order_item_id,
    new_price=199.99
)

Пытаемся изменить цену позиции 1 в заказе 00010242fe8c5a6d1ba2dd792cb16214...
Текущая цена: 58.90
Новое значение цены: 199.99
COMMIT выполнен — цена позиции 1 в заказе 00010242fe8c5a6d1ba2dd792cb16214 изменена с 58.90 на 199.99

In [ ]:
print("Состояние позиции ПОСЛЕ выполнения функции:")
show_order_item(order_id, order_item_id)

Состояние позиции ПОСЛЕ выполнения функции:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,199.99,13.29

## Задание 4. Перевод заказа в статус `delivered` с проверкой текущего состояния

### Бизнес-контекст

В таблице `orders` хранится информация о жизненном цикле заказа интернет-магазина.  
Одним из этапов этого жизненного цикла является доставка заказа клиенту.

Если заказ уже передан перевозчику и находится в статусе `shipped`, приложение должно уметь завершать этот этап обработки: переводить заказ в статус `delivered` и фиксировать дату фактической доставки в поле `order_delivered_customer_date`.

Однако такая операция допустима не всегда. В рамках данного задания будем считать, что заказ можно отметить как доставленный только при выполнении следующих условий:

1. заказ существует;
2. текущий статус заказа равен `shipped`;
3. дата доставки клиенту `order_delivered_customer_date` еще не заполнена.

Если хотя бы одно из этих условий нарушено, операция не должна изменять данные.

### Используемая таблица

В задании используется таблица `orders`, содержащая, в частности, следующие поля:

* `order_id` — уникальный идентификатор заказа;
* `customer_id` — идентификатор клиента;
* `order_status` — текущий статус заказа;
* `order_purchase_timestamp` — дата и время оформления заказа;
* `order_approved_at` — дата подтверждения заказа;
* `order_delivered_carrier_date` — дата передачи заказа перевозчику;
* `order_delivered_customer_date` — дата доставки заказа клиенту;
* `order_estimated_delivery_date` — ожидаемая дата доставки.

### Постановка задачи

Необходимо реализовать функцию `mark_as_delivered(order_id)`, которая принимает:

* `order_id` — идентификатор заказа, который требуется отметить как доставленный.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. получить текущий статус заказа и значение поля `order_delivered_customer_date`;
4. проверить, существует ли заказ с указанным `order_id`;
5. если заказ найден, его статус равен `shipped`, а дата доставки клиенту ещё не заполнена, изменить:
   * `order_status` на `delivered`,
   * `order_delivered_customer_date` на текущее время;
6. явно зафиксировать изменения с помощью `commit()`;
7. если заказ не найден, имеет другой статус или уже содержит дату доставки, выполнить `rollback()`;
8. в случае ошибки также выполнить `rollback()`.

### Дополнительное условие визуальной проверки результата

Перед вызовом функции и после её выполнения необходимо получить строку из таблицы `orders` для одного и того же `order_id` и сравнить:

* значение поля `order_status`;
* значение поля `order_delivered_customer_date`.

Таким образом, в задании нужно продемонстрировать полный цикл:

1. получение исходного состояния строки;
2. проверку текущего статуса заказа;
3. проверку даты доставки клиенту;
4. выполнение транзакционного изменения;
5. фиксацию транзакции через `COMMIT`;
6. повторное чтение строки после завершения операции.

### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Управление транзакцией со стороны Python

Именно Python-код определяет, допустимо ли завершение операции, и принимает решение о вызове `commit()` или `rollback()`.

#### 2. Проверка состояния данных перед изменением

Перед выполнением `UPDATE` необходимо убедиться, что заказ действительно находится в статусе `shipped` и ещё не помечен как доставленный.

#### 3. Контроль результата чтения из базы данных

После выполнения `SELECT` необходимо проверить, что заказ с указанным `order_id` существует. Если строка не найдена, операция должна считаться неуспешной.

#### 4. Наблюдаемость результата

До и после вызова функции необходимо показать строку с одним и тем же `order_id`, чтобы убедиться, что после `COMMIT` статус действительно изменился на `delivered`, а поле `order_delivered_customer_date` было заполнено.

### Ограничения

* Запросы должны быть выполнены как параметризованные;
* Нельзя подставлять значения в SQL через f-строку;
* Нельзя использовать режим автокоммита;
* Обработка ошибок должна быть реализована через `try / except` с вызовом `rollback()`;
* Если заказ не найден, операция должна завершаться без изменения данных;
* Если статус заказа отличается от `shipped`, операция также не должна изменять данные;
* Если дата доставки клиенту уже заполнена, повторное изменение выполнять нельзя.

### Ожидаемый результат

После выполнения задания:

* для заданного заказа со статусом `shipped` значение `order_status` должно измениться на `delivered`;
* поле `order_delivered_customer_date` должно быть заполнено текущим временем;
* изменение должно сохраниться в базе данных только после вызова `commit()`;
* если заказ не найден, имеет другой статус или уже был доставлен, изменение не должно быть выполнено;
* при повторном чтении строки после выполнения функции должны отображаться обновленные значения только в корректном случае.

In [ ]:
def show_order(order_id):
    return pd.read_sql(
        """
        SELECT
            order_id,
            customer_id,
            order_status,
            order_purchase_timestamp,
            order_approved_at,
            order_delivered_carrier_date,
            order_delivered_customer_date,
            order_estimated_delivery_date
        FROM orders
        WHERE order_id = %(order_id)s
        """,
        engine,
        params={"order_id": order_id}
    )


def mark_as_delivered(order_id):

In [ ]:
order_id = '002f19a65a2ddd70a090297872e6d64e'

In [ ]:
print("Состояние заказа ДО выполнения функции:")
show_order(order_id)

Состояние заказа ДО выполнения функции:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,002f19a65a2ddd70a090297872e6d64e,7fa80efb1ef15ca4104627910c29791c,shipped,2018-03-21 13:05:30,2018-03-21 13:15:27,2018-03-22 00:13:35,None,2018-04-16

In [ ]:
mark_as_delivered(order_id)

Пытаемся отметить заказ 002f19a65a2ddd70a090297872e6d64e как доставленный...
Текущий статус заказа: shipped
Дата доставки клиенту: None
COMMIT выполнен — заказ 002f19a65a2ddd70a090297872e6d64e переведен в статус delivered

In [ ]:
print("Состояние заказа ПОСЛЕ выполнения функции:")
show_order(order_id)

Состояние заказа ПОСЛЕ выполнения функции:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,002f19a65a2ddd70a090297872e6d64e,7fa80efb1ef15ca4104627910c29791c,delivered,2018-03-21 13:05:30,2018-03-21 13:15:27,2018-03-22 00:13:35,2026-04-03 15:17:12.224253,2018-04-16

## Задание 5. Удаление позиции из заказа с проверкой, что заказ не станет пустым

### Бизнес-контекст

В таблице `order_items` хранятся товарные позиции заказов интернет-магазина.  
Один заказ может содержать одну или несколько позиций, и каждая из них описывается отдельной строкой.

Иногда клиент хочет удалить одну из позиций из заказа до его окончательной обработки. Однако система не должна допускать ситуацию, при которой после удаления в заказе не останется ни одной позиции.

В рамках данного задания будем считать, что удалить позицию можно только в том случае, если:

1. заказ с указанным `order_id` содержит более одной позиции;
2. позиция с указанным `order_item_id` действительно существует в этом заказе.

Если хотя бы одно из этих условий нарушено, операция не должна изменять данные.

### Используемая таблица

В задании используется таблица `order_items`, содержащая, в частности, следующие поля:

* `order_id` — идентификатор заказа;
* `order_item_id` — номер позиции внутри заказа;
* `product_id` — идентификатор товара;
* `seller_id` — идентификатор продавца;
* `shipping_limit_date` — предельная дата отправки;
* `price` — цена товарной позиции;
* `freight_value` — стоимость доставки.

### Постановка задачи

Необходимо реализовать функцию `remove_item_safe(order_id, order_item_id)`, которая принимает:

* `order_id` — идентификатор заказа;
* `order_item_id` — номер позиции, которую требуется удалить.

Функция должна:

1. установить соединение с базой данных `olist_db`;
2. создать курсор;
3. посчитать количество позиций в заказе;
4. проверить, существует ли позиция с указанными `(order_id, order_item_id)`;
5. если позиция существует и в заказе больше одной позиции, удалить эту строку из таблицы `order_items`;
6. явно зафиксировать изменения с помощью `commit()`;
7. если позиция не найдена или удаление привело бы к пустому заказу, выполнить `rollback()`;
8. в случае ошибки также выполнить `rollback()`.

### Дополнительное условие визуальной проверки результата

Перед вызовом функции и после её выполнения необходимо получить все позиции одного и того же заказа из таблицы `order_items` и сравнить их количество, а также убедиться, что нужная позиция исчезла после выполнения операции.

Таким образом, в задании нужно продемонстрировать полный цикл:

1. получение исходного состояния набора строк;
2. проверку существования удаляемой позиции;
3. проверку количества позиций в заказе;
4. выполнение транзакционного изменения;
5. фиксацию транзакции через `COMMIT`;
6. повторное чтение строк после завершения операции.

### Что требуется продемонстрировать

В рамках задания необходимо показать следующие моменты.

#### 1. Управление транзакцией со стороны Python

Именно Python-код определяет, допустимо ли удаление позиции, и принимает решение о вызове `commit()` или `rollback()`.

#### 2. Проверка бизнес-ограничения перед удалением

Перед выполнением `DELETE` необходимо убедиться, что после удаления в заказе останется хотя бы одна позиция.

#### 3. Контроль результата чтения из базы данных

До удаления необходимо проверить, что позиция заказа с указанными `(order_id, order_item_id)` существует. Если строка не найдена, операция должна считаться неуспешной.

#### 4. Наблюдаемость результата

До и после вызова функции необходимо показать позиции одного и того же заказа, чтобы убедиться, что после `COMMIT` одна строка действительно была удалена.

### Ограничения

* Запросы должны быть выполнены как параметризованные;
* Нельзя подставлять значения в SQL через f-строку;
* Нельзя использовать режим автокоммита;
* Обработка ошибок должна быть реализована через `try / except` с вызовом `rollback()`;
* Если позиция заказа не найдена, операция должна завершаться без изменения данных;
* Если в заказе только одна позиция, удаление выполнять нельзя.

### Ожидаемый результат

После выполнения задания:

* для заданного заказа количество строк в `order_items` должно уменьшиться на единицу;
* строка с указанными `(order_id, order_item_id)` должна исчезнуть из результата выборки;
* изменение должно сохраниться в базе данных только после вызова `commit()`;
* если позиция не найдена или в заказе была только одна строка, удаление не должно быть выполнено;
* при повторном чтении данных после выполнения функции должен отображаться корректный итоговый набор строк.

In [ ]:
def show_order_items(order_id):
    return pd.read_sql(
        """
        SELECT
            order_id,
            order_item_id,
            product_id,
            seller_id,
            shipping_limit_date,
            price,
            freight_value
        FROM order_items
        WHERE order_id = %(order_id)s
        ORDER BY order_item_id
        """,
        engine,
        params={"order_id": order_id}
    )


def remove_item_safe(order_id, order_item_id):

In [ ]:
order_id = '0008288aa423d2a3f00fcb17cd7d8719'
order_item_id = 1

In [ ]:
print("Позиции заказа ДО выполнения функции:")
show_order_items(order_id)

Позиции заказа ДО выполнения функции:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.9,13.37
1,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.9,13.37

In [ ]:
remove_item_safe(
    order_id=order_id,
    order_item_id=order_item_id
)

Пытаемся удалить позицию 1 из заказа 0008288aa423d2a3f00fcb17cd7d8719...
Количество позиций в заказе: 2
COMMIT выполнен — позиция 1 успешно удалена из заказа 0008288aa423d2a3f00fcb17cd7d8719

In [ ]:
print("Позиции заказа ПОСЛЕ выполнения функции:")
show_order_items(order_id)

Позиции заказа ПОСЛЕ выполнения функции:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.9,13.37